package model;
// Generated Jun 7, 2016 11:29:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="bsm"
)
public class Address  implements java.io.Serializable {


     private int addressId;
     private int addressNo;
     private String streetName;
     private String city;
     private String province;
     private String country;
     private Set tenants = new HashSet(0);
     private Set nextofkins = new HashSet(0);
     private Set employees = new HashSet(0);

    public Address() {
    }

	
    public Address(int addressId, int addressNo, String streetName, String city, String province, String country) {
        this.addressId = addressId;
        this.addressNo = addressNo;
        this.streetName = streetName;
        this.city = city;
        this.province = province;
        this.country = country;
    }
    public Address(int addressId, int addressNo, String streetName, String city, String province, String country, Set tenants, Set nextofkins, Set employees) {
       this.addressId = addressId;
       this.addressNo = addressNo;
       this.streetName = streetName;
       this.city = city;
       this.province = province;
       this.country = country;
       this.tenants = tenants;
       this.nextofkins = nextofkins;
       this.employees = employees;
    }
   
     @Id 

    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="AddressId", unique=true, nullable=false)
    public int getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(int addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="AddressNo", nullable=false)
    public int getAddressNo() {
        return this.addressNo;
    }
    
    public void setAddressNo(int addressNo) {
        this.addressNo = addressNo;
    }

    
    @Column(name="StreetName", nullable=false, length=25)
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    
    @Column(name="City", nullable=false, length=25)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Province", nullable=false, length=25)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    
    @Column(name="Country", nullable=false, length=25)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set getTenants() {
        return this.tenants;
    }
    
    public void setTenants(Set tenants) {
        this.tenants = tenants;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set getNextofkins() {
        return this.nextofkins;
    }
    
    public void setNextofkins(Set nextofkins) {
        this.nextofkins = nextofkins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


