package model;
// Generated Jun 7, 2016 11:29:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name="contract"
    ,catalog="bsm"
)
public class Contract  implements java.io.Serializable {


     private int contractId;
     private Room room;
     private Date startDate;
     private Date endDate;
     private Set tenants = new HashSet(0);

    public Contract() {
    }

	
    public Contract(int contractId, Room room, Date startDate, Date endDate) {
        this.contractId = contractId;
        this.room = room;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public Contract(int contractId, Room room, Date startDate, Date endDate, Set tenants) {
       this.contractId = contractId;
       this.room = room;
       this.startDate = startDate;
       this.endDate = endDate;
       this.tenants = tenants;
    }
   
     @Id 

    
    @Column(name="ContractId", unique=true, nullable=false)
    public int getContractId() {
        return this.contractId;
    }
    
    public void setContractId(int contractId) {
        this.contractId = contractId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RoomId", nullable=false)
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="StartDate", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EndDate", nullable=false, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contract")
    public Set getTenants() {
        return this.tenants;
    }
    
    public void setTenants(Set tenants) {
        this.tenants = tenants;
    }




}


