package model;
// Generated Jun 7, 2016 11:29:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * House generated by hbm2java
 */
@Entity
@Table(name="house"
    ,catalog="bsm"
)
public class House  implements java.io.Serializable {


     private int houseId;
     private Employee employee;
     private String houseAddress;
     private int noOfRooms;
     private Set rooms = new HashSet(0);

    public House() {
    }

	
    public House(int houseId, Employee employee, String houseAddress, int noOfRooms) {
        this.houseId = houseId;
        this.employee = employee;
        this.houseAddress = houseAddress;
        this.noOfRooms = noOfRooms;
    }
    public House(int houseId, Employee employee, String houseAddress, int noOfRooms, Set rooms) {
       this.houseId = houseId;
       this.employee = employee;
       this.houseAddress = houseAddress;
       this.noOfRooms = noOfRooms;
       this.rooms = rooms;
    }
   
     @Id 

    
    @Column(name="HouseId", unique=true, nullable=false)
    public int getHouseId() {
        return this.houseId;
    }
    
    public void setHouseId(int houseId) {
        this.houseId = houseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EmpId", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="HouseAddress", nullable=false, length=50)
    public String getHouseAddress() {
        return this.houseAddress;
    }
    
    public void setHouseAddress(String houseAddress) {
        this.houseAddress = houseAddress;
    }

    
    @Column(name="NoOfRooms", nullable=false)
    public int getNoOfRooms() {
        return this.noOfRooms;
    }
    
    public void setNoOfRooms(int noOfRooms) {
        this.noOfRooms = noOfRooms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="house")
    public Set getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Set rooms) {
        this.rooms = rooms;
    }




}


