package model;
// Generated Jun 7, 2016 11:29:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="bsm"
)
public class Payment  implements java.io.Serializable {


     private int paymentId;
     private Tenant tenant;
     private Employee employee;
     private Room room;
     private double paymentAmount;
     private Date paymnetDate;
     private String paymentType;

    public Payment() {
    }

	
    public Payment(int paymentId, Tenant tenant, Employee employee, Room room, double paymentAmount, Date paymnetDate) {
        this.paymentId = paymentId;
        this.tenant = tenant;
        this.employee = employee;
        this.room = room;
        this.paymentAmount = paymentAmount;
        this.paymnetDate = paymnetDate;
    }
    public Payment(int paymentId, Tenant tenant, Employee employee, Room room, double paymentAmount, Date paymnetDate, String paymentType) {
       this.paymentId = paymentId;
       this.tenant = tenant;
       this.employee = employee;
       this.room = room;
       this.paymentAmount = paymentAmount;
       this.paymnetDate = paymnetDate;
       this.paymentType = paymentType;
    }
   
     @Id 

    
    @Column(name="PaymentId", unique=true, nullable=false)
    public int getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(int paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TenantId", nullable=false)
    public Tenant getTenant() {
        return this.tenant;
    }
    
    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EmpId", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RoomId", nullable=false)
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }

    
    @Column(name="PaymentAmount", nullable=false, precision=12)
    public double getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void setPaymentAmount(double paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PaymnetDate", nullable=false, length=10)
    public Date getPaymnetDate() {
        return this.paymnetDate;
    }
    
    public void setPaymnetDate(Date paymnetDate) {
        this.paymnetDate = paymnetDate;
    }

    
    @Column(name="paymentType", length=25)
    public String getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }




}


