package model;
// Generated Jun 7, 2016 11:29:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tenant generated by hbm2java
 */
@Entity
@Table(name="tenant"
    ,catalog="bsm"
)
public class Tenant  implements java.io.Serializable {


     private String tenantId;
     private Contract contract;
     private Nextofkin nextofkin;
     private Employee employee;
     private Address address;
     private String name;
     private String surname;
     private Character gender;
     private String email;
     private String contactNo;
     private Set payments = new HashSet(0);

    public Tenant() {
    }

	
    public Tenant(String tenantId, String email) {
        this.tenantId = tenantId;
        this.email = email;
    }
    public Tenant(String tenantId, Contract contract, Nextofkin nextofkin, Employee employee, Address address, String name, String surname, Character gender, String email, String contactNo, Set payments) {
       this.tenantId = tenantId;
       this.contract = contract;
       this.nextofkin = nextofkin;
       this.employee = employee;
       this.address = address;
       this.name = name;
       this.surname = surname;
       this.gender = gender;
       this.email = email;
       this.contactNo = contactNo;
       this.payments = payments;
    }
   
     @Id 

    
    @Column(name="TenantId", unique=true, nullable=false, length=15)
    public String getTenantId() {
        return this.tenantId;
    }
    
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contractid")
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="KinId")
    public Nextofkin getNextofkin() {
        return this.nextofkin;
    }
    
    public void setNextofkin(Nextofkin nextofkin) {
        this.nextofkin = nextofkin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empid")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AddressId")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

    
    @Column(name="name", length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=25)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="gender", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }

    
    @Column(name="email", nullable=false, length=35)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="contactNo", length=10)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tenant")
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }




}


